// <auto-generated />
using System;
using AlunosApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlunosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AlunosApi.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Aluno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            CreatedAt = new DateTime(2023, 10, 14, 21, 38, 46, 906, DateTimeKind.Local).AddTicks(5508),
                            Email = "mariapenha@gmail.com",
                            Name = "Maria Da Penha"
                        },
                        new
                        {
                            Id = 2,
                            Age = 47,
                            CreatedAt = new DateTime(2023, 10, 14, 21, 38, 46, 906, DateTimeKind.Local).AddTicks(5523),
                            Email = "zefederico@hotmail.com",
                            Name = "Zé Federico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
